### ISSUE TITLE
Token <ALALIGNE> and return type

### ISSUE THREAD

**Issue by halfa** [halfa/yaka-compiler#8]
```JAVA
      Consumed token: <";" at line 27 column 18>
      Call:   instruction
        Call:   ecriture
          Consumed token: <"ALALIGNE" at line 28 column 9>
        Return: ecriture
      Return: instruction
 exception.BadTypeException: in function sup : Syntax Error: bad type: Error in 
assignement: Expected type BOOLEAN but receive INTEGER 
	at compiler.Expression.assertAssignementType(Expression.java:291)
	at compiler.Make.assertAssignementType(Make.java:279)
	at compiler.Yaka.affectation(Yaka.java:487)
	at compiler.Yaka.instruction(Yaka.java:393)
	at compiler.Yaka.suiteInstr(Yaka.java:371)
	at compiler.Yaka.bloc(Yaka.java:166)
	at compiler.Yaka.analyse(Yaka.java:70)
	at compiler.Yaka.main(Yaka.java:37)
    Consumed token: <";" at line 28 column 17>
```

**Comment by Entilore** [comment]
It seems to be good
